Traceback (most recent call last):
  File "poznan_bot.py", line 3, in <module>
    import telegram
ImportError: No module named 'telegram'
Traceback (most recent call last):
  File "poznan_bot.py", line 3, in <module>
    import telegram
ImportError: No module named 'telegram'
Traceback (most recent call last):
  File "poznan_bot.py", line 3, in <module>
    import telegram
ImportError: No module named 'telegram'
2017-01-31 15:02:31,652 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update.
2017-01-31 15:02:38,445 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update.
2017-01-31 15:03:14,218 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update.
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
2017-03-07 00:01:01,171 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15.0)",)': /bot261419062:AAFe2GkE3xUgDf3ZdMu7qmgCf9CLOTWgg6E/getUpdates
2017-03-10 15:57:10,255 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15.0)",)': /bot261419062:AAFe2GkE3xUgDf3ZdMu7qmgCf9CLOTWgg6E/getUpdates
2017-03-10 15:57:24,210 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-03-11 21:37:40,546 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15.0)",)': /bot261419062:AAFe2GkE3xUgDf3ZdMu7qmgCf9CLOTWgg6E/getUpdates
2017-03-16 17:12:34,239 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:12:35,260 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:12:36,783 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:12:39,061 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:12:42,460 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:12:47,548 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:12:55,170 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:13:06,597 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:13:23,724 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:13:49,400 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:14:27,907 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:14:57,933 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:15:27,987 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:15:58,019 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:16:28,049 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:16:58,077 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:17:28,104 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:17:58,130 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:18:28,188 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:18:58,226 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:19:28,253 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:19:58,280 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:20:28,306 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:20:58,331 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:21:28,364 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:21:58,436 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
2017-03-16 17:22:28,463 - telegram.ext.updater - ERROR - Error while getting Updates: Unauthorized
